version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DEBUG=True
      - LOG_LEVEL="INFO"
      - ALLOWED_HOSTS=127.0.0.1, .localhost, *
      - DATABASE_URL="postgres://postgres:postgres@db:5432/feira"
      - SECRET_KEY=!8z6x+11-&vp3f+uy37&cur^wv&-l4v5vd+*)2pqzea=)a%++w
      - SECRET_KEY="eb*xnd%dbcj*u0q^y75s!mz9)87(_i@vz&i@w4r-pc3rp1duf1"
    entrypoint: "./wait-for-it.sh db:5432 -s -t 120 -- ./entrypoint-compose.sh"
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=brasilprev
    networks:
      - dev

networks:
  dev: