version: '3'

services:
  db:
    image: postgres:10.5-alpine
    container_name: container_database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=brasilprev
    networks:
      - dev

  api:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    container_name: container_api
    environment:
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgres://postgres:postgres@db:5432/brasilprev
      - SECRET_KEY=!8z6x+11-&vp3f+uy37&cur^wv&-l4v5vd+*)2pqzea=)a%++w
      - FILENAME_LOG_APP=/var/log/app/app.log
      - FILENAME_LOG_GUNICORN=/var/log/app/gunicorn.log
    command: /app/entrypoint.sh
    ports:
      - 8000:8000
    networks: 
      - dev
    depends_on:
      - db

networks:
  dev: 
